l1 = set(map(int, input('Enter 1st set: ').split()))
print(l1)
l2 = set(map(int, input('Enter 2nd set: ').split()))
print(l2)
print ("Union:", l1|l2)
print ("Intersection:", l1&l2)
print ("Difference(1st - 2nd):", l1-l2)
print ("Difference(2nd - 1st):", l2-l1)
print ("Union:", l1^l2)
